export const PACKET_TYPE_LENGTH = 2;
export const PACKET_VERSION_LENGTH = 1;
export const PACKET_SEQUENCE = 4;
export const PACKET_PAYLOAD_LENGTH = 2;

// TODO: S2C,C2S 넣을건지 확인 후 수정 필요.

export const PACKET_TYPE = {
  // 에러
  ERROR_NOTIFICATION: 1,

  // 회원가입 및 로그인
  REGISTER_REQUEST: 2,
  REGISTER_RESPONSE: 3,
  LOGIN_REQUEST: 4,
  LOGIN_RESPONSE: 5,

  // 매칭
  MATCH_REQUEST: 6,
  MATCH_NOTIFICATION: 7,

  // 게임 시작
  GAME_START_REQUEST: 8,
  GAME_START_NOTIFICATION: 9,

  // 건물 구입 및 알림
  PURCHASE_BUILDING_REQUEST: 10,
  PURCHASE_BUILDING_RESPONSE: 11,
  ADD_ENEMY_BUILDING_NOTIFICATION: 12,

  // 유닛 스폰 및 알림
  SPAWN_UNIT_REQUEST: 13,
  SPAWN_UNIT_RESPONSE: 14,
  SPAWN_ENEMY_UNIT_NOTIFICATION: 15,

  // 유닛 공격 및 알림
  ATTACK_UNIT_REQUEST: 16,
  ATTACK_UNIT_RESPONSE: 17,
  ENEMY_UNIT_ATTACK_NOTIFICATION: 18,

  // 유닛 사망 및 알림
  UNIT_DEATH_NOTIFICATION: 19,
  ENEMY_UNIT_DEATH_NOTIFICATION: 20,

  // 거점 진입 및 성공여부 알림
  ENTER_CHECKPOINT_NOTIFICATION: 21,
  TRY_OCCUPATION_NOTIFICATION: 22,
  PAUSE_OCCUPATION_NOTIFICATION: 23,
  OCCUPATION_TIMER_RESET_NOTIFICATION: 24,
  OCCUPATION_SUCCESS_NOTIFICATION: 25,

  // 성채 공격 및 알림
  ATTACK_BASE_REQUEST: 26,
  ATTACK_BASE_RESPONSE: 27,
  BASE_ATTACKED_NOTIFICATION: 28,

  // 게임 종료
  GAME_OVER_NOTIFICATION: 29,
  GAME_END_NOTIFICATION: 30,

  // 상태 동기화
  LOCATION_NOTIFICATION:31,
  LOCATION_SYNC_NOTIFICATION:32,
};

export const PACKET_TYPE_REVERSED = Object.fromEntries(
  Object.entries(PACKET_TYPE).map(([key, value]) => [value, key]),
);
