export const PACKET_TYPE_LENGTH = 2;
export const PACKET_VERSION_LENGTH = 1;
export const PACKET_SEQUENCE = 4;
export const PACKET_ERROR_CODE = 1;
export const PACKET_PAYLOAD_LENGTH = 2;

// TODO: S2C,C2S 넣을건지 확인 후 수정 필요.

export const PACKET_TYPE = {
  // 회원가입 및 로그인
  REGISTER_REQUEST: 1,
  REGISTER_RESPONSE: 2,
  LOGIN_REQUEST: 3,
  LOGIN_RESPONSE: 4,

  // 매칭
  MATCH_REQUEST: 5,
  MATCH_NOTIFICATION: 6,

  // 게임 시작
  GAME_START_REQUEST: 7,
  GAME_START_NOTIFICATION: 8,

  // 건물 구입 및 알림
  PURCHASE_BUILDING_REQUEST: 9,
  PURCHASE_BUILDING_RESPONSE: 10,
  ADD_ENEMY_BUILDING_NOTIFICATION: 11,

  // 유닛 스폰 및 알림
  SPAWN_UNIT_REQUEST: 12,
  SPAWN_UNIT_RESPONSE: 13,
  SPAWN_ENEMY_UNIT_NOTIFICATION: 14,

  // 유닛 공격 및 알림
  ATTACK_UNIT_REQUEST: 15,
  ATTACK_UNIT_RESPONSE: 16,
  ENEMY_UNIT_ATTACK_NOTIFICATION: 17,

  // 유닛 사망 및 알림
  UNIT_DEATH_NOTIFICATION: 18,
  ENEMY_UNIT_DEATH_NOTIFICATION: 19,

  // 거점 진입 및 성공여부 알림
  ENTER_CHECKPOINT_NOTIFICATION: 20,
  TRY_OCCUPATION_NOTIFICATION: 21,
  PAUSE_OCCUPATION_NOTIFICATION: 22,
  OCCUPATION_TIMER_RESET_NOTIFICATION: 23,
  OCCUPATION_SUCCESS_NOTIFICATION: 24,

  // 성채 공격 및 알림
  ATTACK_BASE_REQUEST: 25,
  ATTACK_BASE_RESPONSE: 26,
  BASE_ATTACKED_NOTIFICATION: 27,

  // 게임 종료
  GAME_OVER_NOTIFICATION: 28,
  GAME_END_NOTIFICATION: 29,

  // 에러
  ERROR_NOTIFICATION: 30,
};

export const PACKET_TYPE_REVERSED = Object.fromEntries(
  Object.entries(PACKET_TYPE).map(([key, value]) => [value, key]),
);
