export const PACKET_TYPE_LENGTH = 2;
export const PACKET_VERSION_LENGTH = 1;
export const PACKET_SEQUENCE = 4;
export const PACKET_PAYLOAD_LENGTH = 2;

// TODO: S2C,C2S 넣을건지 확인 후 수정 필요.

export const PACKET_TYPE = Object.freeze({
  // 에러
  ERROR_NOTIFICATION: 1,

  // 인증
  AUTH_REQUEST: 2,
  AUTH_RESPONSE: 3,

  // 게임 시작
  GAME_START_REQUEST: 4,
  GAME_START_NOTIFICATION: 5,

  // 건물 구매
  PURCHASE_BUILDING_REQUEST: 6,
  PURCHASE_BUILDING_RESPONSE: 7,
  ADD_ENEMY_BUILDING_NOTIFICATION: 8,

  // 유닛 생성
  SPAWN_UNIT_REQUEST: 9,
  SPAWN_UNIT_RESPONSE: 10,
  SPAWN_ENEMY_UNIT_NOTIFICATION: 11,

  // 유닛 공격
  ATTACK_UNIT_REQUEST: 12,
  ATTACK_UNIT_RESPONSE: 13,
  ENEMY_UNIT_ATTACK_NOTIFICATION: 14,

  // 유닛 사망
  UNIT_DEATH_NOTIFICATION: 15,
  ENEMY_UNIT_DEATH_NOTIFICATION: 16,

  // 체크포인트 점령
  ENTER_CHECKPOINT_NOTIFICATION: 17,
  EXIT_CHECKPOINT_NOTIFICATION: 18,
  TRY_OCCUPATION_NOTIFICATION: 19,
  PAUSE_OCCUPATION_NOTIFICATION: 20,
  OCCUPATION_TIMER_RESET_NOTIFICATION: 21,
  OCCUPATION_SUCCESS_NOTIFICATION: 22,

  // 성채공격
  ATTACK_BASE_REQUEST: 23,
  ATTACK_BASE_RESPONSE: 24,
  BASE_ATTACKED_NOTIFICATION: 25,

  // 게임 종료
  GAME_OVER_NOTIFICATION: 26,
  GAME_END_NOTIFICATION: 27,

  // 상태 동기화
  LOCATION_NOTIFICATION: 28,
  LOCATION_SYNC_NOTIFICATION: 29,
  MINERAL_SYNC_NOTIFICATION: 30,

  // 힐 스킬 관련
  HEAL_UNIT_REQUEST: 31,
  HEAL_UNIT_RESPONSE: 32,
  ENEMY_HEAL_UNIT_NOTIFICATION: 33,

  // 버프 스킬 관련
  BUFF_UNIT_REQUEST: 34,
  BUFF_UNIT_RESPONSE: 35,
  ENEMY_BUFF_UNIT_NOTIFICATION: 36,

  // 애니메이션 관련
  UNIT_ANIMATION_NOTIFICATION: 37,
  ENEMY_UNIT_ANIMATION_NOTIFICATION: 38,

  // 공격 스펠
  ATTACK_SPELL_REQUEST: 45,
  ATTACK_SPELL_RESPONSE: 46,
  ENEMY_ATTACK_SPELL_NOTIFICATION: 47,

  // 힐 스펠
  HEAL_SPELL_REQUEST: 48,
  HEAL_SPELL_RESPONSE: 49,
  ENEMY_HEAL_SPELL_NOTIFICATION: 50,

  // 버프 스펠
  BUFF_SPELL_REQUEST: 51,
  BUFF_SPELL_RESPONSE: 52,
  ENEMY_BUFF_SPELL_NOTIFICATION: 53,

  // 스턴 스펠
  STUN_SPELL_REQUEST: 54,
  STUN_SPELL_RESPONSE: 55,
  ENEMY_STUN_SPELL_NOTIFICATION: 56,
});

export const PACKET_TYPE_REVERSED = Object.fromEntries(
  Object.entries(PACKET_TYPE).map(([key, value]) => [value, key]),
);
